from datetime import datetime, UTC
from pathlib import Path
from reliabilityops.models import CheckResult, IncidentClassification


def generate_markdown_report(result: CheckResult, classification: IncidentClassification) -> str:
    evidence = "\n".join(f"- {item}" for item in classification.evidence)
    actions = "\n".join(f"{idx}. {item}" for idx, item in enumerate(classification.recommended_actions, start=1))

    return f"""# Incident Report

## Summary

ReliabilityOps detected an API check result for `{result.service}` at `{result.endpoint}`.

## Affected Service

- Service: {result.service}
- Endpoint: {result.endpoint}
- Status Code: {result.status_code}
- Latency: {result.latency_ms}ms
- Success: {result.success}

## Likely Root Cause

{classification.category}

## Severity

{classification.severity}

## Confidence

{classification.confidence}%

## Evidence

{evidence}

## Recommended Actions

{actions}

## Generated By

ReliabilityOps

## Generated At

{datetime.now(UTC).isoformat()}
"""


def write_report(result: CheckResult, classification: IncidentClassification, output_dir: str = "reports") -> Path:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
    service = result.service.replace(" ", "_").lower()
    path = Path(output_dir) / f"incident_{service}_{timestamp}.md"
    path.write_text(generate_markdown_report(result, classification), encoding="utf-8")
    return path
